# Generated by Django 2.2.4 on 2019-09-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_bath_door_dressroom_kitchen_livingroom_veranda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veranda',
        ),
    ]
